## Emby global config for Nginx-UI.
## Keep only http-level directives here.

js_path /etc/nginx/conf.d;
js_import embyConfig from emby/config.js;
js_import embyMain from emby/main.js;
js_import embyPeriodics from emby/common/periodics.js;
js_import embyItems from emby/modules/emby-items.js;
js_import embyLive from emby/modules/emby-live.js;
js_import embySearch from emby/modules/emby-search.js;
js_import embySystem from emby/modules/emby-system.js;
js_import embyVMedia from emby/modules/emby-v-media.js;

js_shared_dict_zone zone=routeL1Dict:8M timeout=15m evict;
js_shared_dict_zone zone=routeL2Dict:16M timeout=15m evict;
# js_shared_dict_zone zone=routeL3Dict:32M timeout=15m evict;
js_shared_dict_zone zone=idemDict:512K timeout=10s evict;
js_shared_dict_zone zone=tmpDict:512K timeout=60s evict;
js_shared_dict_zone zone=versionDict:32M timeout=11h evict;

proxy_cache_path /var/cache/nginx/images levels=1:2 keys_zone=emby_images:100m max_size=10g inactive=30d use_temp_path=off;
proxy_cache_path /var/cache/nginx/subtitles levels=1:2 keys_zone=emby_subtitles:10m max_size=1g inactive=30d use_temp_path=off;
